### ISSUE TITLE
Search is broken: org.eclipse.ui.views.navigator.NavigatorDragAdapter cannot be found

### ISSUE THREAD

**Issue by basilevs** [eclipse/org.eclipse.rcptt#41]
Search is broken. Failing test: SearchTextInTags

```
eclipse.buildId=4.28.0.I20230605-0440
java.version=17.0.4.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_GE
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /Users/vasiligulevich/xored/rcptt/ws/rcptt/../aut-org.eclipse.platform.ide2-3 -dev file:/Users/vasiligulevich/xored/rcptt/ws/rcptt/.metadata/.plugins/org.eclipse.pde.core/org.eclipse.platform.ide2/dev.properties -os macosx -ws cocoa -arch aarch64 -consoleLog

org.eclipse.ui
Error
Sat Mar 16 22:26:54 GET 2024
Unhandled event loop exception

java.lang.NoClassDefFoundError: org/eclipse/ui/views/navigator/NavigatorDragAdapter
	at org.eclipse.rcptt.search.Q7SearchResultPage.addDragAdapters(Q7SearchResultPage.java:165)
	at org.eclipse.rcptt.search.Q7SearchResultPage.configureTreeViewer(Q7SearchResultPage.java:193)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.createViewer(AbstractTextSearchViewPage.java:736)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.createControl(AbstractTextSearchViewPage.java:579)
	at org.eclipse.search2.internal.ui.SearchView.doCreatePage(SearchView.java:356)
	at org.eclipse.ui.part.PageBookView.createPage(PageBookView.java:369)
	at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:696)
	at org.eclipse.search2.internal.ui.SearchView.partActivated(SearchView.java:333)
	at org.eclipse.search2.internal.ui.SearchView.internalShowSearchPage(SearchView.java:422)
	at org.eclipse.search2.internal.ui.SearchView.showSearchResult(SearchView.java:393)
	at org.eclipse.search2.internal.ui.SearchViewManager.showNewSearchQuery(SearchViewManager.java:77)
	at org.eclipse.search2.internal.ui.SearchViewManager$1.queryAdded(SearchViewManager.java:51)
	at org.eclipse.search2.internal.ui.QueryManager.fireAdded(QueryManager.java:96)
	at org.eclipse.search2.internal.ui.QueryManager.addQuery(QueryManager.java:73)
	at org.eclipse.search2.internal.ui.InternalSearchUI.addQuery(InternalSearchUI.java:311)
	at org.eclipse.search2.internal.ui.InternalSearchUI.runSearchInBackground(InternalSearchUI.java:171)
	at org.eclipse.search.ui.NewSearchUI.runQueryInBackground(NewSearchUI.java:136)
	at org.eclipse.search.ui.NewSearchUI.runQueryInBackground(NewSearchUI.java:109)
	at org.eclipse.rcptt.search.Q7SearchPageImpl.performAction(Q7SearchPageImpl.java:236)
	at org.eclipse.search.internal.ui.SearchDialog.performAction(SearchDialog.java:500)
	at org.eclipse.search.internal.ui.util.ExtendedDialogWindow.buttonPressed(ExtendedDialogWindow.java:167)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent_aroundBody2(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget$AjcClosure3.run(Widget.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$2$2f127892proceed(RecordingAspect.aj:96)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$2$2f127892(RecordingAspect.aj:120)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent_aroundBody4(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget$AjcClosure5.run(Widget.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$1$bd9fb3e7proceed(RecordingAspect.aj:41)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$1$bd9fb3e7(RecordingAspect.aj:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1536)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTEvents.sendEventRaw(SWTEvents.java:93)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTEvents.sendEvent(SWTEvents.java:195)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$3.run(SWTUIPlayer.java:901)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$ExecRunnable.run(SWTUIPlayer.java:2700)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open_aroundBody0(Window.java:799)
	at org.eclipse.jface.window.Window.open(Window.java:785)
	at org.eclipse.search.internal.ui.OpenSearchDialogAction.run(OpenSearchDialogAction.java:60)
	at org.eclipse.search.internal.ui.OpenSearchDialogAction.run(OpenSearchDialogAction.java:50)
	at org.eclipse.search.internal.ui.OpenSearchDialogPageAction$SearchPageAction.run(OpenSearchDialogPageAction.java:131)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent_aroundBody2(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget$AjcClosure3.run(Widget.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$2$2f127892proceed(RecordingAspect.aj:96)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$2$2f127892(RecordingAspect.aj:120)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent_aroundBody4(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget$AjcClosure5.run(Widget.java:1)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$1$bd9fb3e7proceed(RecordingAspect.aj:41)
	at org.eclipse.rcptt.tesla.recording.aspects.RecordingAspect.ajc$around$org_eclipse_rcptt_tesla_recording_aspects_RecordingAspect$1$bd9fb3e7(RecordingAspect.aj:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1536)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTEvents.sendEventRaw(SWTEvents.java:93)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTEvents.sendEvent(SWTEvents.java:74)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTEvents.sendEvent(SWTEvents.java:64)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer.clickMenuItem(SWTUIPlayer.java:1007)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer.access$14(SWTUIPlayer.java:969)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$3.run(SWTUIPlayer.java:864)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$ExecRunnable.run(SWTUIPlayer.java:2700)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.ClassNotFoundException: org.eclipse.ui.views.navigator.NavigatorDragAdapter cannot be found by org.eclipse.rcptt.search_2.5.5.202403142044
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 102 more
```

**Comment by basilevs** [comment]
These should be fixed in #21 but still fail with "'key' - 0 matches in working set 'WorkingSet2' (Search in Descriptions)"

**Comment by basilevs** [comment]
Modified tests are [still failing](https://ci.eclipse.org/rcptt/job/Pull_requests/view/change-requests/job/PR-21/34/testReport/junit/(root)/TEST-tests/Start_Build_and_Test___RCPTT_Test___SearchTextInContexts/). The menu item "Deselect working set" is disabled.
We could try to wait for its activation.

**Comment by basilevs** [comment]
Tests are fixed
