### ISSUE TITLE
InterruptedException does not stop Runner

### ISSUE THREAD

**Issue by basilevs** [eclipse/org.eclipse.rcptt#55]
After following exception runner has not stopped and a lot of further tests [has failed](https://ci.eclipse.org/rcptt/view/active/job/Pull_requests/job/master/27/artifact/rcpttTests/target/results/out.txt):

```
!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 22:59:04.811
!MESSAGE Pass 739 (777) processed. 5 failed. spent: 263:52, 13:10 mins remaining. UndoDeleteProjectWithoutDeleteFromDiskByEditMenu. time: 15840ms 
Pass 739 (777) processed. 5 failed. spent: 263:52, 13:10 mins remaining. UndoDeleteProjectWithoutDeleteFromDiskByEditMenu. time: 15840ms 

!ENTRY org.eclipse.rcptt.launching 4 0 2024-03-20 23:04:12.830
!MESSAGE error getting interpreter state
!STACK 0
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at org.eclipse.rcptt.ecl.internal.core.Process.waitFor(Process.java:68)
	at org.eclipse.rcptt.internal.launching.aut.BaseAutLaunch.executeAndTakeAll(BaseAutLaunch.java:348)
	at org.eclipse.rcptt.internal.launching.aut.BaseAutLaunch.dumpState(BaseAutLaunch.java:898)
	at org.eclipse.rcptt.internal.launching.aut.BaseAutLaunch.lambda$1(BaseAutLaunch.java:961)
	at org.eclipse.rcptt.internal.launching.aut.BaseAutLaunch$1.run(BaseAutLaunch.java:266)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:04:24.888
!MESSAGE [AUT-0] Finished: UndoDeleteProjectWithoutDeleteFromDiskByHotKey.test in 308073, Execution timed out after 300 seconds (739 from 777)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:04:24.889
!MESSAGE [AUT-0] Starting: UndoDeletingTwoContextsInTest.test (740 from 777)

!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 23:04:24.987
!MESSAGE Fail 740 (777) processed. 6 failed. spent: 269:12, 13:03 mins remaining. UndoRedoDeleteProjectWithoutDeleteFromDiskByHotKey. time: 308073ms  Cause: Execution timed out after 300 seconds
Fail 740 (777) processed. 6 failed. spent: 269:12, 13:03 mins remaining. UndoRedoDeleteProjectWithoutDeleteFromDiskByHotKey. time: 308073ms  Cause: Execution timed out after 300 seconds

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:04:54.016
!MESSAGE [AUT-0] Finished: UndoDeletingTwoContextsInTest.test in 27139 (740 from 777)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:04:54.018
!MESSAGE [AUT-0] Starting: UndoRedoDeleteFolderByEditMenu.test (741 from 777)

!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 23:04:54.019
!MESSAGE Pass 741 (777) processed. 6 failed. spent: 269:41, 12:42 mins remaining. UndoDeletingTwoContextsInTest. time: 27139ms 
Pass 741 (777) processed. 6 failed. spent: 269:41, 12:42 mins remaining. UndoDeletingTwoContextsInTest. time: 27139ms 

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:05:05.325
!MESSAGE [AUT-0] Finished: UndoRedoDeleteFolderByEditMenu.test in 10285, class org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl cannot be cast to class org.eclipse.rcptt.tesla.core.protocol.BooleanResponse (org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl and org.eclipse.rcptt.tesla.core.protocol.BooleanResponse are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @673e1cf2) (741 from 777)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:05:05.326
!MESSAGE [AUT-0] Starting: UndoRedoDeletingTestSuiteByHotKeys.test (742 from 777)

!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 23:05:05.329
!MESSAGE Fail 742 (777) processed. 7 failed. spent: 269:52, 12:19 mins remaining. UndoRedoDeleteFolderByEditMenu. time: 10285ms  Cause: class org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl cannot be cast to class org.eclipse.rcptt.tesla.core.protocol.BooleanResponse (org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl and org.eclipse.rcptt.tesla.core.protocol.BooleanResponse are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @673e1cf2)
Fail 742 (777) processed. 7 failed. spent: 269:52, 12:19 mins remaining. UndoRedoDeleteFolderByEditMenu. time: 10285ms  Cause: class org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl cannot be cast to class org.eclipse.rcptt.tesla.core.protocol.BooleanResponse (org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl and org.eclipse.rcptt.tesla.core.protocol.BooleanResponse are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @673e1cf2)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:05:23.191
!MESSAGE [AUT-0] Finished: UndoRedoDeletingTestSuiteByHotKeys.test in 16479 (742 from 777)
.....

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:15:18.328
!MESSAGE [AUT-0] Starting: get-editor should not activate editor instead of view.test (775 from 777)

!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 23:15:18.359
!MESSAGE Fail 775 (777) processed. 27 failed. spent: 280:05, 0:21 mins remaining. get-editor should not activate another editor. time: 10252ms  Cause: Assertion of itemCount failed: expected:<2> but was:<1>.
Fail 775 (777) processed. 27 failed. spent: 280:05, 0:21 mins remaining. get-editor should not activate another editor. time: 10252ms  Cause: Assertion of itemCount failed: expected:<2> but was:<1>.

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:15:28.055
!MESSAGE [AUT-0] Finished: get-editor should not activate editor instead of view.test in 8857, class org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl cannot be cast to class org.eclipse.rcptt.tesla.core.protocol.BooleanResponse (org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl and org.eclipse.rcptt.tesla.core.protocol.BooleanResponse are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @673e1cf2) (775 from 777)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:15:28.056
!MESSAGE [AUT-0] Starting: get-item should fail when index parameter is out of bound.test (776 from 777)

!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 23:15:28.070
!MESSAGE Fail 776 (777) processed. 28 failed. spent: 280:15, 0:00 mins remaining. get-editor should not activate editor instead of view. time: 8857ms  Cause: class org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl cannot be cast to class org.eclipse.rcptt.tesla.core.protocol.BooleanResponse (org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl and org.eclipse.rcptt.tesla.core.protocol.BooleanResponse are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @673e1cf2)
Fail 776 (777) processed. 28 failed. spent: 280:15, 0:00 mins remaining. get-editor should not activate editor instead of view. time: 8857ms  Cause: class org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl cannot be cast to class org.eclipse.rcptt.tesla.core.protocol.BooleanResponse (org.eclipse.rcptt.tesla.core.protocol.impl.SelectResponseImpl and org.eclipse.rcptt.tesla.core.protocol.BooleanResponse are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @673e1cf2)

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:15:34.284
!MESSAGE [AUT-0] Finished: get-item should fail when index parameter is out of bound.test in 5214 (776 from 777)

!ENTRY org.eclipse.rcptt.runner 4 0 2024-03-20 23:15:34.377
!MESSAGE Pass 777 (777) processed. 28 failed. spent: 280:21, 0:00 mins remaining. get-item should fail when index parameter is out of bound. time: 5214ms 
Pass 777 (777) processed. 28 failed. spent: 280:21, 0:00 mins remaining. get-item should fail when index parameter is out of bound. time: 5214ms 
Failed Tests:
findReferencesToContextInTests
findReferencesToTestInTestSuite
Undo\RedoTestWhichIsUsedInTestSuite
TakeScreenshot
VerifyIgnoredLines
WorkspaceContextRemoveTest
UpdateTagsViewAfterDeleteBunchObjects
Use * as any string 
UndoRedoDeletingTestSuiteFromEditMenu
UndoRedoDeleteFolderByEditMenu
get-editor should not activate another editor
UndoRedoDeleteProjectWithoutDeleteFromDiskByHotKey
findReferencesToContextInRelatedProject
RefreshControlStateInAssertionMode
VerifyText
Set Breakpoint In Proc_Step Into_Step Return
ErrLogVerification_NEGATIVE Case Required Entry Not Found (Plugin Pattern)
Undo\RedoInContextDescription
WorkspaceContextImportProjectTest
Undo/Redo in Control Panel
WorkspaceContextCopyPasteTest
VerifyWhiteSpaceCharacters
get-editor should not activate editor instead of view
findReferencesToContextInGroupContext
Job error is captured by Error Log Verification
UpdateTagsViewAfterDeleteObject
VerifyWorkspace
FolderContextCreation

!ENTRY org.eclipse.rcptt.runner 1 0 2024-03-20 23:15:34.378
!MESSAGE Shut down AUTs: executed
Process terminated. Shut down AUTs
```

**Comment by basilevs** [comment]
Hypothesis, the interruption is caused by a timeout. [I'm removing the delays](https://github.com/eclipse/org.eclipse.rcptt/commit/3467716fc7dbe602aebb216a73cb7030bdc878ca?diff=unified&w=0)

**Comment by basilevs** [comment]
The test that fails to stop, continues execution and corrupts report and result of the next one.

**Comment by basilevs** [comment]
`org.eclipse.rcptt.ecl.server.tcp.SessionRequestHandler.SessionRequestHandler(Socket, boolean)` relies on `socket.isClosed()` to detect client shutdown (which happens on cancel), but in modern Java, socket is not closed when client shuts down.
