### ISSUE TITLE
Seeing Java heap Issue

### ISSUE THREAD

**Issue by sramshek** [eclipse/org.eclipse.rcptt#67]
We are running rcptt tests using latest runner snapshot and seeing Java heap memory errors

```java
INFO] !ENTRY org.eclipse.core.jobs 4 2 2024-04-10 22:00:36.608
[INFO] !MESSAGE An internal error occurred during: "Debug Event Dispatch".
[INFO] !STACK 0
[INFO] java.lang.OutOfMemoryError: Java heap space
[INFO] 	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1375)
[INFO] 	at java.base/java.lang.StringConcatHelper.newArray(StringConcatHelper.java:497)
[INFO] 	at java.base/java.lang.String.join(String.java:3269)
[INFO] 	at java.base/java.lang.String.join(String.java:3335)
[INFO] 	at org.eclipse.pde.internal.build.site.PDEState.querySystemPackages(PDEState.java:552)
[INFO] 	at org.eclipse.pde.internal.build.site.PDEState.getSystemPackages(PDEState.java:487)
[INFO] 	at org.eclipse.pde.internal.core.TargetPlatformHelper.getSystemPackages(TargetPlatformHelper.java:392)
[INFO] 	at org.eclipse.pde.internal.core.TargetPlatformHelper.addEnvironmentProperties(TargetPlatformHelper.java:379)
[INFO] 	at org.eclipse.pde.internal.core.TargetPlatformHelper.getPlatformProperties(TargetPlatformHelper.java:366)
[INFO] 	at org.eclipse.pde.internal.core.MinimalState.initializePlatformProperties(MinimalState.java:259)
[INFO] 	at org.eclipse.pde.internal.core.PDEState.<init>(PDEState.java:70)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.getModels(Q7ExternalLaunchDelegate.java:899)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.access$0(Q7ExternalLaunchDelegate.java:898)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate$BundlesToLaunchCollector.addPluginBundle(Q7ExternalLaunchDelegate.java:700)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate$BundlesToLaunchCollector.access$1(Q7ExternalLaunchDelegate.java:699)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.collectBundles(Q7ExternalLaunchDelegate.java:834)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.collectBundlesCheck(Q7ExternalLaunchDelegate.java:810)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.preLaunchCheck(Q7ExternalLaunchDelegate.java:645)
[INFO] 	at org.eclipse.pde.launching.AbstractPDELaunchConfiguration.launch(AbstractPDELaunchConfiguration.java:139)
[INFO] 	at org.eclipse.rcptt.launching.ext.Q7ExternalLaunchDelegate.launch(Q7ExternalLaunchDelegate.java:128)
``` 

I have below vmargs set in project pom.xml
 <vmArg>-Xms2048m</vmArg>
<vmArg>-Xmx3072m</vmArg>
<vmArg>-XX:MaxPermSize=2048m</vmArg>

**Comment by basilevs** [comment]
This is a Runner error. Are you sure that -Xmx3072m is Runner argument and not AUT's? Where in XML hierarchy do you define it?
