### ISSUE TITLE
NullPointerException when workspace contains bad .target file

### ISSUE THREAD

**Issue by benken-parasoft** [eclipse/org.eclipse.rcptt#69]
I had a ".target" file in my workspace that is not actually a target platform definition.  When I try launching my application under test then I would see a NullPointerException logged.  It is getting thrown from TargetPlatformManager.findTarget() which does the following:
```java
    def = getTargetDefinition(handle);
    String name = def.getName();
```
A NullPointerException is thrown because "def" is null.  I believe this code is simply missing a null pointer check to skip over the non-parseable target platform.

For now, I simply have to remove the bad .target file from my workspace.

**Comment by basilevs** [comment]
What are steps to reproduce? How can target file be invalid?

**Comment by benken-parasoft** [comment]
1. Put some random file in your workspace where its name happens to end in ".target".  It could be an empty file or something that isn't XML.
2. Open "Windows > Preferences > Plugin-in Development > Target Platform" then you should see an error about the bad file.  However, keep "Running Platform" or some valid target still selected there and click OK.
3. Open "Run > Run Configurations..." then right-click "Application Under Test" then click "New Configuration".  Create an new AUT then click Apply.  An error is logged which isn't necessarily unexpected as long as RCPTT actually saved the run config correctly but not sure:
```
Error reading target definition
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
...
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at org.eclipse.pde.internal.core.target.TargetDefinitionPersistenceHelper.initFromXML(TargetDefinitionPersistenceHelper.java:149)
	at org.eclipse.pde.internal.core.target.TargetDefinition.setContents(TargetDefinition.java:779)
	at org.eclipse.pde.internal.core.target.AbstractTargetHandle.getTargetDefinition(AbstractTargetHandle.java:35)
	at org.eclipse.rcptt.launching.target.TargetPlatformManager.getTargetDefinition(TargetPlatformManager.java:230)
	at org.eclipse.rcptt.launching.target.TargetPlatformManager.deleteTargetPlatform(TargetPlatformManager.java:180)
	at org.eclipse.rcptt.internal.launching.ext.Q7TargetPlatformManager$1.launchConfigurationRemoved(Q7TargetPlatformManager.java:176)
	at org.eclipse.debug.internal.core.LaunchManager$ConfigurationNotifier.run(LaunchManager.java:217)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.debug.internal.core.LaunchManager$ConfigurationNotifier.notify(LaunchManager.java:204)
	at org.eclipse.debug.internal.core.LaunchManager.launchConfigurationDeleted(LaunchManager.java:2032)
	at org.eclipse.debug.internal.core.LaunchConfiguration.delete(LaunchConfiguration.java:335)
	at org.eclipse.debug.internal.core.LaunchConfigurationWorkingCopy.doSave0(LaunchConfigurationWorkingCopy.java:263)
```
4. Run the new AUT config.  The launch fails and a NullPointerException is logged:
```
An internal error occurred during: "Launching my_aut".
java.lang.NullPointerException: Cannot invoke "org.eclipse.pde.core.target.ITargetDefinition.getName()" because "def" is null
	at org.eclipse.rcptt.launching.target.TargetPlatformManager.findTarget(TargetPlatformManager.java:144)
	at org.eclipse.rcptt.launching.configuration.Q7LaunchConfigurationDelegate.preLaunchCheck(Q7LaunchConfigurationDelegate.java:137)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:769)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1038)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

In my case, my workspace just happened to have some file where the name ends in ".target".  It is not an Eclipse target platform definition and has nothing to do with that.  It is used for something entirely unrelated to Eclipse but just happens to live in one of the source projects in my workspace.  Of course, I have a valid target platform selected in the Eclipse preferences.  I wasn't specifically looking at error logs, just configuring my AUT run config as usual then saw the launch fail with NullPointerException.

**Comment by basilevs** [comment]
To reproduce more reliably, stop RCPTT, delete workspace/.metadata/.plugins/org.eclipse.pde.core/.local_targets and restart.
