### ISSUE TITLE
Drag & Drop from palette no longer works with GEF 3.19+

### ISSUE THREAD

**Issue by ptziegler** [eclipse/org.eclipse.rcptt#79]
The method `getDrawerFigure()` of the internal DrawerEditPart has been replaced by `getFigure()` with https://github.com/eclipse/gef-classic/commit/6e1b9e34a7aff8c365cf12156672c1a6c020d86d#diff-6dac2412767db37bfa839d2cfde85e545656c32e4b9351ab4cb2795e852a1d57.

Trying to select & drag an element from the palette fails with the following exception:

```
org.eclipse.rcptt.tesla.internal.core.TeslaExecutionFailedException: org.eclipse.rcptt.tesla.gef.GefProcessor.handleFigureMouseCommand:764
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$ExecRunnable.run(SWTUIPlayer.java:2709)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4058)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at de.dsa.prodis.automation.AutomationApplication.start(AutomationApplication.java:328)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Caused by: java.lang.NoSuchMethodError: 'org.eclipse.gef.internal.ui.palette.editparts.DrawerFigure org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart.getDrawerFigure()'
	at org.eclipse.rcptt.tesla.gef.GefProcessor$4.run(GefProcessor.java:775)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$ExecRunnable.run(SWTUIPlayer.java:2703)
```

**Comment by ptziegler** [comment]
This already represents itself in form of a compilation error when using the 2024-03 target platform definition. My proposition is to use getFigure() instead. On newer versions of GEF, this method returns the DrawerFigure (as opposed to an IFigure), but to remain backwards compatible, one has to do an explicit type cast.

**Comment by Greglar4** [comment]
We are also seeing this problem, and it's blocking us from upgrading our RCP application to 2024-03.
