### ISSUE TITLE
With the latest eclipse(2024-03) some functions like drag and drop does not work.

### ISSUE THREAD

**Issue by sathirauop** [eclipse/org.eclipse.rcptt#83]
With the 2.5.5 nightly build until 2023-12 the drag drop function works fine when runinning test cases. With the latest eclipse 2024-03 the eclipse have updated certain methods like DrawerFigure and they are required from the rcptt to do the drag and drop method. 
So it gives this error log.

org.eclipse.rcptt.tesla.internal.core.TeslaExecutionFailedException: org.eclipse.rcptt.tesla.gef.GefProcessor.handleFigureMouseCommand:764
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$ExecRunnable.run(SWTUIPlayer.java:2709)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.NoSuchMethodError: 'org.eclipse.gef.internal.ui.palette.editparts.DrawerFigure org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart.getDrawerFigure()'
	at org.eclipse.rcptt.tesla.gef.GefProcessor$4.run(GefProcessor.java:775)
	at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer$ExecRunnable.run(SWTUIPlayer.java:2703)
	... 26 more

**Comment by sathirauop** [comment]
I used this nightly build because 2.5.4 does not work with eclipse versions after 2022-12 eclipse version

**Comment by ptziegler** [comment]
> Caused by: java.lang.NoSuchMethodError: 'org.eclipse.gef.internal.ui.palette.editparts.DrawerFigure org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart.getDrawerFigure()'

That sounds like a duplicate of https://github.com/eclipse/org.eclipse.rcptt/issues/79

> I used this nightly build because 2.5.4 does not work with eclipse versions after 2022-12 eclipse version

Which nightly-build do you mean? This error doesn't show up in the 2.5.5.202406121414 Nightly.

**Comment by sathirauop** [comment]
Dear Patrick Ziegler,

Thank you very much for your prompt reply. I appreciate your assistance. To
clarify, I was indeed using a nightly build prior to version
2.5.5.202406121414 Nightly. My apologies for any confusion. I am pleased to
report that everything is now functioning correctly.

If it is alright, I would like to ask a few more questions regarding this
platform. I am currently working on a custom Eclipse plugin and need to run
some MVP test cases with each new Eclipse release. Until now, we have
conducted these tests manually, but I have been tasked with automating them.

I noticed that the stable release 2.5.4 does not work with the newer
versions of Eclipse. Could you please inform me when the new stable release
2.5.5 is expected to be available?

Additionally, as a recent graduate, I am eager to learn more about
contributing to open source projects, specifically within the Eclipse
platform and RCPTT tool development. Could you kindly provide some guidance
on how I might begin contributing to these projects?

Thank you once again for your valuable time and assistance.

Best regards,

Sathira Basnyake

**Comment by sathirauop** [comment]
As this issue is fixed through the https://github.com/eclipse/org.eclipse.rcptt/issues/79 I will close this issue. Thank you everyone.

**Comment by ptziegler** [comment]
@sathirauop I'm just an occasional contributor, not a commiter.

> Could you please inform me when the new stable release
2.5.5 is expected to be available?

Anything related to the release management is something @basilevs has to initiate.

> Could you kindly provide some guidance
on how I might begin contributing to these projects?

Each Eclipse project _should_ have a README/CONTRIBUTING file which gives you a general outline on how to set up your work environment. Then you can create issues and pull requests as you would with any other projects and usually, one of the committers will try to help you with sorting everything else out.

**Comment by sathirauop** [comment]
Thank you very much Patrick I will look into those

**Comment by basilevs** [comment]
> Additionally, as a recent graduate, I am eager to learn more about contributing to open source projects, specifically within the Eclipse platform and RCPTT tool development. Could you kindly provide some guidance on how I might begin contributing to these projects?

A good first contribution would be to migrate [RCPTT Contribution guide](https://wiki.eclipse.org/RCPTT/Contribution_Guide) to Github.


> Could you please inform me when the new stable release 2.5.5 is expected to be available?

Release 2.5.5 activities are being tracked in #35.

**Comment by Mailaender** [comment]
> A good first contribution would be to migrate [RCPTT Contribution guide](https://wiki.eclipse.org/RCPTT/Contribution_Guide) to Github as wiki.eclipse.org has been phased out.

The wiki is disabled or at least not visible to non-committers.

**Comment by basilevs** [comment]
> The wiki is disabled or at least not visible to non-committers.

Github's wiki for this project? As a commiter I have an option to create a first page, but for contribution guide It may make sense to put the information in Git repository root as CONTRIBUTING.md.

If you think that Wiki is a requirement, I could try to create it, but I envision more access control issues  with Wiki than with PRs.

**Comment by basilevs** [comment]
Apparently I have created a [project's Wiki](https://github.com/eclipse-rcptt/org.eclipse.rcptt/wiki) anyway
