### ISSUE TITLE
NPE in SWTUIPlayer.selectMenu()

### ISSUE THREAD

**Issue by basilevs** [eclipse/org.eclipse.rcptt#87]
# Test steps

Run
```
get-menu -path "Window/New Window" | click
with [get-window -index 1 ] {
	close
	get-menu -path "Window/Show View/Other..." | click
} 
```
# Expected result
Test fails with a human readable message about closed window.
# Actual result
Test fails with an exception stacktrace as a failure reason:
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.rcptt.tesla.internal.ui.player.SWTUIElement.getKind()" because "currentParent" is null
        at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer.selectMenu(SWTUIPlayer.java:1338)
        at org.eclipse.rcptt.tesla.internal.ui.player.SWTUIPlayer.select(SWTUIPlayer.java:314)
        at org.eclipse.rcptt.tesla.internal.ui.processors.SWTUIProcessor.select(SWTUIProcessor.java:2199)
        at org.eclipse.rcptt.tesla.internal.core.TeslaProcessorManager.select(TeslaProcessorManager.java:87)
        at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.handleSelect(AbstractTeslaClient.java:110)
        at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.execute(AbstractTeslaClient.java:298)
        at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.doOneCommand(AbstractTeslaClient.java:247)
        at org.eclipse.rcptt.tesla.internal.core.AbstractTeslaClient.processNext(AbstractTeslaClient.java:129)
        at org.eclipse.rcptt.tesla.ecl.impl.TeslaBridge$2.doProcessing(TeslaBridge.java:102)
        at org.eclipse.rcptt.tesla.swt.events.TeslaEventManager.doProcessing(TeslaEventManager.java:109)
        at org.eclipse.rcptt.tesla.swt.aspects.DisplayAspect.ajc$around$org_eclipse_rcptt_tesla_swt_aspects_DisplayAspect$1$e269b158(DisplayAspect.aj:87)
        at org.eclipse.swt.widgets.Display.sleep(Display.java:4767)
```
# Workaround
Prefix get-menu with `get-window -index 0 |`

# Notes
The same problem happens randomly in a test where Eclipse windows are opened and created multiple times. Some sort of concurrency seems to happen here.

**Comment by basilevs** [comment]
After multiple attempts, I had to postpone further work.
